namespace: abaldeweg
name: playbook
version: 1.1.0
readme: README.md
authors:
  - André Baldeweg <a@baldeweg.org>
description: Installs some basic roles for machines that PHP php and JavaScript apps.
platforms:
  - name: Ubuntu
    versions:
      - bionic
tags:
  - collection
repository: https://github.com/abaldeweg/playbook
issues: https://github.com/abaldeweg/playbook/issues
