namespace: abaldeweg
name: playbook
version: 4.0.1
readme: README.md
authors:
  - André Baldeweg <a@baldeweg.org>
description: Installs some basic roles for machines that run PHP and JavaScript apps.
license:
tags:
  - collection
repository: https://github.com/abaldeweg/playbook
issues: https://github.com/abaldeweg/playbook/issues
