namespace: abaldeweg
name: playbook
version: 1.0.0
readme: README.md
authors:
  - André Baldeweg <a@baldeweg.org>
description: Installs some basic roles for machines that PHP php and JavaScript apps.
tags:
  - collection
repository: https://gitlab.com/a.baldeweg/playbook
issues: https://gitlab.com/a.baldeweg/playbook/-/issues
