namespace: abaldeweg
name: playbook
version: 0.1.0
readme: README.md
authors:
  - André Baldeweg <a@baldeweg.org>
description: Installs some basic roles for machines that run php or node apps.
tags:
  - collection
repository: https://gitlab.com/a.baldeweg/playbook
issues: https://gitlab.com/a.baldeweg/playbook/-/issues
