---
- name: Upgrade Packages
  apt:
    upgrade: dist
    update_cache: yes

- name: Install Packages
  apt:
    pkg:
      - imagemagick
      - libmagickcore-6.q16-6-extra
      - python3-openssl
      - python3-pymysql
      - sudo
      - curl
      - apt-transport-https
      - dirmngr
      - unzip
      - wget
      - rsync
      - nano
      - make
    state: present
    update_cache: yes

