---
- name: Install Packages
  apt:
    pkg:
      - imagemagick
      - python3-openssl
      - python3-pymysql
      - sudo
      - curl
      - apt-transport-https
      - dirmngr
      - unzip
      - wget
      - rsync
      - nano
      - git
    state: present
    update_cache: yes

