---
- name: Add Key
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    state: present

- name: Add Repo
  apt_repository:
    repo: deb https://deb.nodesource.com/node_12.x {{ ansible_distribution_release }} main
    state: present

- name: Install Packages
  apt:
    name: nodejs
    state: present
    update_cache: yes
