---
- name: Add Key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 7BF576066ADA65728FC7E70A8C47BE8E75BCA694
    state: present

- name: Add Repo
  apt_repository:
    repo: deb http://ppa.launchpad.net/certbot/certbot/ubuntu bionic main
    state: present

- name: Install Packages
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: true
  vars:
    packages:
      - software-properties-common
      - certbot
      - python-certbot-apache
