---
- name: Install Required Packages
  apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
    state: present
    update_cache: true

- name: Install Docker Engine
  script: scripts/engine
  args:
    creates: /usr/bin/docker

- name: Install Docker Compose
  script: scripts/compose
  args:
    creates: /usr/local/bin/docker-compose
